title: でんでんガァデン
author: あれく
email: 
description: ""
baseurl: "" 
url: "https://denden.garden"
twitter_username: 
github_username: 
permalink: /:year/:month/:day/:title

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true

feed:
  excerpt_only: true
  categories:
    - broadcast
    - signal-log

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
